manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: d45cb3c26fc113357dfc035965e51c84e13e218d
      import: app/west.yml
  self:
    path: config
